"""
add execution node model

Revision ID: 1309f2c716b6
Revises: 6289c01972eb
Create Date: 2026-02-27 20:17:00.947773

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "1309f2c716b6"
down_revision: str | Sequence[str] | None = "6289c01972eb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
