"""
add execution model

Revision ID: 6289c01972eb
Revises: b02eb9268d85
Create Date: 2026-02-27 19:52:49.416003

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "6289c01972eb"
down_revision: str | Sequence[str] | None = "b02eb9268d85"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
